name: Youtube Video Deck V2

on: [push]

env:
  SECRET_KEY: secret
  DATABASE_DBNAME: dbname
  DATABASE_USERNAME: user
  DATABASE_PASSWORD: password
  DATABASE_HOSTNAME: localhost
  GOOGLE_API_KEY: google-api-key

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      # Set up a postgres database alongside the tests
      postgres:
        image: postgres:12.0
        env:
          POSTGRES_PASSWORD: "password"
          POSTGRES_USER: "username"
          POSTGRES_DB: "database"
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: pytest -m "not webtest"
      env:
        GOOGLE_API_KEY: "google-api-key"
        DATABASE_USERNAME: "username"
        DATABASE_DBNAME: "database"
        DATABASE_PASSWORD: "password"
        DATABASE_HOSTNAME: localhost
        SECRET_KEY: "secret"
